version: "3.8"

services:
  redis:
    image: redis:7
    container_name: local-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
